services:
  scheduler:
    image: pyromeow/task-scheduler:latest
    ports:
      - "7540:7540"
    volumes:
      - ./data:/app/data
    environment:
      - SALT_JWT=${SALT_JWT}
      - TODO_DBFILE=/app/data/scheduler.db
      - TODO_PASSWORD=${TODO_PASSWORD}